export const sdgInfo: Record<number, { title: string; color: string }> = {
  1: { title: "No Poverty", color: "#E5243B" },
  2: { title: "Zero Hunger", color: "#DDA63A" },
  3: { title: "Good Health & Well-Being", color: "#4C9F38" },
  4: { title: "Quality Education", color: "#C5192D" },
  5: { title: "Gender Equality", color: "#FF3A21" },
  6: { title: "Clean Water & Sanitation", color: "#26BDE2" },
  7: { title: "Affordable & Clean Energy", color: "#FCC30B" },
  8: { title: "Decent Work & Economic Growth", color: "#A21942" },
  9: { title: "Industry, Innovation & Infrastructure", color: "#FD6925" },
  10: { title: "Reduced Inequalities", color: "#DD1367" },
  11: { title: "Sustainable Cities & Communities", color: "#FD9D24" },
  12: { title: "Responsible Consumption & Production", color: "#BF8B2E" },
  13: { title: "Climate Action", color: "#3F7E44" },
  14: { title: "Life Below Water", color: "#0A97D9" },
  15: { title: "Life on Land", color: "#56C02B" },
  16: { title: "Peace, Justice & Strong Institutions", color: "#00689D" },
  17: { title: "Partnerships for the Goals", color: "#19486A" },
};
